### ISSUE TITLE
csv_final.py retornando erro

### ISSUE THREAD

**Issue by jhsbarbosa** [ericbrasiln/ferramentas_scielo_v2#10]
Após a finalização da conversão de XML para CSV feita pelo run.py, ao tentar criar o CSV contendo todos os metadados, o script csv_final.py retorna o seguinte erro:

>... line 9, in df_final
    data = time.strftime("%Y-%m-%d_%H%-M%-S") # Define o dia e a hora
ValueError: Invalid format string

**Comment by jhsbarbosa** [comment]
Resolução: correção de erro de digitação: de "%H%-M%-S" para "%H-%M-%S"

**Comment by ericbrasiln** [comment]
Merge #12
