### ISSUE TITLE
infos_xml.py retornando muitos 'None' na coluna 'pub_date'

### ISSUE THREAD

**Issue by jhsbarbosa** [ericbrasiln/ferramentas_scielo_v2#11]
O script não retorna erro, mas da forma como a função de coleta de informações para compor a coluna 'pub_date' estava escrita, retornava muitos valores 'None' nesta coluna (cerca de 60mil dentro de um dataframe com cerca de 80 mil linhas). Mudei a função para que passasse a considerar apenas o ano das publicações e isso baixou significativamente a quantidade de 'None' na coluna (menos de 100)

**Comment by ericbrasiln** [comment]
Merge #12
