### ISSUE TITLE
Dúvida em relação ao ISSN do código scielo_rev_v2.py

### ISSUE THREAD

**Issue by FelipeHiginodePaula** [ericbrasiln/ferramentas_scielo_v2#2]
Bom dia. Estou tendo uma dúvida em relação a parte da inserção do ISSN, pois tentei colocar o código de algumas revistas da Scielo mas parece não reconhecer e dá erro. Gostaria de uma ajuda nessa parte do código. Se possível gostaria que me fornecesse um exemplo de ISSN funcional para que eu possa usar de exemplo para verificar o problema. Quando executo o código, abre o google chrome mas aparece que o periódico não foi encontrado. Os códigos que eu estou procurando são os seguintes:
ISSN-Online	Revista						                Qualis
1983-8239	CADERNO CRH (ONLINE)				A1
1809-4449	CADERNOS PAGU					        A1
1678-4588	DADOS - REVISTA DE CI NCIAS SOCIAIS	A1
0011-5258	DADOS (RIO DE JANEIRO. IMPRESSO)		A1
1678-9857	REVISTA DE ANTROPOLOGIA			        A1
1809-4554	TEMPO SOCIAL (ONLINE)			        A1
2175-7801	REVISTA PHYSIS					        A2
0725-5136	THESIS ELEVEN					        A2
2077-0472	AGRICULTURE					                B1
De qualquer forma, desde já eu agradeço.

**Comment by ericbrasiln** [comment]
Boa tarde, @bigfil18 
Obrigado pelo contato.

Nessa versão do programa, a opção de raspar uma lista específica de periódicos não se dá através da lista de ISSNs, pois o novo site do Scielo utiliza a abreviatura do nome dos periódicos para gerar a url. Por exemplo, para a revista Cadernos Pagu, a sigla é cpa (veja imagem)

![cpa](https://user-images.githubusercontent.com/58128421/153475449-82c2a633-13c6-483d-8168-109da884b095.PNG)

Essa explicação está aqui: https://github.com/ericbrasiln/ferramentas_scielo_v2#scielo_rev_v2py

> scielo_rev_v2.py
Nesse script é possível raspar uma revista ou uma lista de revistas específicas através de seu nome.
Possui as mesmas características do scielo_v2.py, porém a definição da(s) revista(s) a ser(em) raspada(s) é feita através da abreviação do nome da revista conforme URL da revista no site do Scielo.br.
Por exemplo, se vc pretende raspar os arquivos da revista Almanack, acesse a página inicial da revista no repositório e encontre a abreviação de seu título na URL.
https://www.scielo.br/j/alm/
Nesse caso, o abreviação do nome da revista é alm. Esse termo deve ser informado para o programa.


Lembrando que para você executar o programa apenas para uma lista específica de periódicos, é preciso utilizar o arquivo `scielo_rev_v2.py`

Ontem atualizei o repositório incluindo a arquivo de citação que pode ser visto no [README.md](https://github.com/ericbrasiln/ferramentas_scielo_v2#como-citar) ou diretamente [aqui](https://github.com/ericbrasiln/ferramentas_scielo_v2/blob/main/CITATION.cff).

Espero ter ajudado. Veja se funciona.
Me de um retorno pra saber se posso fechar o ticket.

**Comment by ericbrasiln** [comment]
Boa tarde, @bigfil18 

Você conseguiu executar? 

Acabei de publicar uma versão atualizada corrigindo erros.

Estou fechando a issue, mas se ainda tiver probelmas pode reabri-la.

**Comment by ericbrasiln** [comment]
Acabei de fazer o release da nova versão: https://github.com/LABHDUFBA/ferramentas_scielo_v2/releases/tag/v2.1

Também atualizei a documentação: https://labhdufba.github.io/ferramentas_scielo_v2
