### ISSUE TITLE
Scielo_v2.py retornando erro na raspagem

### ISSUE THREAD

**Issue by jhsbarbosa** [ericbrasiln/ferramentas_scielo_v2#4]
O script está dando erro ao tentar iniciar a raspagem das edições da revista "Bolema: Boletim de Educação Matemática"

Segue cópia do log:

Link da edição: https://www.scielo.br/j/bolema/aop

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
[WDM] - Driver [\.wdm\drivers\chromedriver\win32\102.0.5005.61\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:51179/devtools/browser/d9b14fc3-f0eb-4d95-8fef-93e600023453
Traceback (most recent call last):
  File "\ferramentas_scielo_v2\scielo_v2.py", line 77, in <module>
    main()
  File "\ferramentas_scielo_v2\scielo_v2.py", line 73, in main
    revistas(diretorio, link, link_final, name, saveMode)
  File "\ferramentas_scielo_v2\revistas.py", line 41, in revistas
    get_issue(diretorio, link, issue_link, pasta, saveMode)
  File "\ferramentas_scielo_v2\issue_xml.py", line 62, in get_issue
    journal = driver.find_element(By.TAG_NAME,'h1').text
  File "\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"h1"}
  (Session info: headless chrome=102.0.5005.63)
Stacktrace:
Backtrace:
        Ordinal0 [0x0035D953+2414931]
        Ordinal0 [0x002EF5E1+1963489]
        Ordinal0 [0x001DC6B8+837304]
        Ordinal0 [0x00209500+1021184]
        Ordinal0 [0x0020979B+1021851]
        Ordinal0 [0x00236502+1205506]
        Ordinal0 [0x002244E4+1131748]
        Ordinal0 [0x00234812+1198098]
        Ordinal0 [0x002242B6+1131190]
        Ordinal0 [0x001FE860+976992]
        Ordinal0 [0x001FF756+980822]
        GetHandleVerifier [0x005CCC62+2510274]
        GetHandleVerifier [0x005BF760+2455744]
        GetHandleVerifier [0x003EEABA+551962]
        GetHandleVerifier [0x003ED916+547446]
        Ordinal0 [0x002F5F3B+1990459]
        Ordinal0 [0x002FA898+2009240]
        Ordinal0 [0x002FA985+2009477]
        Ordinal0 [0x00303AD1+2046673]
        BaseThreadInitThunk [0x76B8FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77987A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77987A4E+238]

**Comment by ericbrasiln** [comment]
Oi @jhsbarbosa 
Precisamos de um tempinho de dedicação pra entender o que aconteceu com o código.

Eu também não estou conseguindo rodar. Mas só vou conseguir tempo pra ver isso no final de julho.

Mas aqui no caso desse erro, diz que não existe a tag `h1`:
```
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"h1"}
```

Parece que essa é uma edição `ahead of print` e quando clico nesse link https://www.scielo.br/j/bolema/aop o que aparece é que não existem artigos, logo a tag `h1` não existe.

![image](https://user-images.githubusercontent.com/58128421/176269131-a34e837c-88a2-4549-9da7-76c083ad9629.png)

Vai no `issue_xml.py` linha 62 e tenta colocar um try/except  aqui: `journal = driver.find_element(By.TAG_NAME,'h1').text` 
Pra dizer que  tenta achar o `h1`se não achar passa.

Tavlez isso funcione.

Agora os problemas que estão dando pra mim são outros! 😄  E ainda não tive tempo de investigar.

Abraços

**Comment by ericbrasiln** [comment]
Boa tarde @jhsbarbosa 
Corrigi a questão que gerava o erro apontado por você.

Veja o PR #7 que vc encontra as mudanças que fiz.

Uma das alterações, buscando diminuir o uso de memória da ferrramenta, acabou demandando um novo método de uso do webdirver pelo Selenium. Agora é preciso ter o webdriver GeckoDriver para Firefox baixado e incluído no PATH de sua máquina.
Ainda vou incluir essas informações na documentação da ferramenta nos próximos dias. Mas vc pode achar o arquivo para [baixar aqui](https://github.com/mozilla/geckodriver/releases), [informações oficiais aqui](https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html) e uma ajuda nessa pergunta do [StackOverflow aqui](https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path/40208762#40208762).

Quando conseguir testar me avise. Abraços

**Comment by ericbrasiln** [comment]
Acabei de fazer o release da nova versão: https://github.com/LABHDUFBA/ferramentas_scielo_v2/releases/tag/v2.1

Também atualizei a documentação: https://labhdufba.github.io/ferramentas_scielo_v2
