### ISSUE TITLE
run.py retornando erro

### ISSUE THREAD

**Issue by jhsbarbosa** [ericbrasiln/ferramentas_scielo_v2#9]
Após a finalização da raspagem, ao rodar o run.py para transformar os XML em CSV, o script retorna o seguinte erro:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 15: invalid continuation byte

**Comment by jhsbarbosa** [comment]
Resolução: a codificação inicial da conversão foi mudada para 'latin-1', mantendo a conversão para 'utf-8-sig' no csv_final.py

**Comment by ericbrasiln** [comment]
Muito obrigado, @jhsbarbosa 
Testei suas alterações e realizei o merge do seu branch para o main. Vou fechar as outras issues tb.
